
var _score = GlobalReaderEmitter("score").request("amount", 0);

if (_score < 150) {
	
	push_generator(
		choose(
			GENERATOR_TYPES.ITERATOR,
			GENERATOR_TYPES.ITERATOR,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.ELEVATOR,
		)
	);
	
	return;
}

if (_score < 400) {
	
	push_generator(
		choose(
			GENERATOR_TYPES.ITERATOR,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.ELEVATOR,
			GENERATOR_TYPES.ELEVATOR,
			
			GENERATOR_TYPES.ITERATOR,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.ELEVATOR,
			GENERATOR_TYPES.ELEVATOR,
			
			GENERATOR_TYPES.INDEFINITE,
		)
	);
	
	return;
}

if (_score < 650) {
	
	push_generator(
		choose(
			GENERATOR_TYPES.ITERATOR,
			GENERATOR_TYPES.ITERATOR,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.ELEVATOR,
			GENERATOR_TYPES.INDEFINITE,
		)
	);
	
	return;
}

if (_score < 800) {
	
	push_generator(
		choose(
			GENERATOR_TYPES.ITERATOR,
			GENERATOR_TYPES.LADDER,
			GENERATOR_TYPES.ELEVATOR,
			GENERATOR_TYPES.ELEVATOR,
			GENERATOR_TYPES.INDEFINITE,
			GENERATOR_TYPES.INDEFINITE,
		)
	);
	
	return;
}

push_generator(
	choose(
		GENERATOR_TYPES.ITERATOR, 
		GENERATOR_TYPES.LADDER,
		GENERATOR_TYPES.ELEVATOR,
		GENERATOR_TYPES.INDEFINITE,
	)
);
